version: "3"
volumes:
  grafana_data:
  db_data:
networks:
  monitor:
    driver: bridge
services:
  proxy:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    networks:
      - monitor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana
      - grafana2
  grafana-db:
    container_name: grafana-db
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: grafana123
      POSTGRES_USER: grafana
      POSTGRES_DB: grafana
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - monitor
  grafana:
    container_name: grafana
    image: grafana/grafana:7.4.1
    networks:
      - monitor
    expose:
      - 3000
    environment:
      - "GF_DEFAULT_INSTANCE_NAME=${HOSTNAME}"
      - "GF_DATABASE_URL=postgres://grafana:grafana123@grafana-db:5432/grafana"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_USERS_ALLOW_SIGN_UP=false"
#      - "GF_SMTP_ENABLED=true"
#      - "GF_SMTP_HOST=mailserver.com:25"
#      - "GF_SMTP_SKIP_VERIFY=true"
#      - "GF_SMTP_FROM_ADDRESS=admin@grafana-container.com"
#      - "GF_SMTP_FROM_NAME=Grafana-container"
    volumes:
#      - grafana_data:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins
#      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - grafana-db

  grafana2:
    container_name: grafana2
    image: grafana/grafana:7.4.1
    networks:
      - monitor
    expose:
      - 3000
    environment:
      - "GF_DEFAULT_INSTANCE_NAME=${HOSTNAME}"
      - "GF_DATABASE_URL=postgres://grafana:grafana123@grafana-db:5432/grafana"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_USERS_ALLOW_SIGN_UP=false"
#      - "GF_SMTP_ENABLED=true"
#      - "GF_SMTP_HOST=mailserver.com:25"
#      - "GF_SMTP_SKIP_VERIFY=true"
#      - "GF_SMTP_FROM_ADDRESS=admin@grafana-container.com"
#      - "GF_SMTP_FROM_NAME=Grafana-container"
    volumes:
#      - grafana_data:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins
#      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - grafana-db
